export default [
  {
    id: 1,
    name: "squigg",
    fov: { min: 20, max: 25 },
    density: { min: 0.05, max: 0.16 },
    strength: { min: 4, max: 10 },
    frequency: { min: 0.54, max: 4 },
    amplitude: { min: 1.4, max: 4.7 },
    intensity: { min: 0.26, max: 0.78 },
    scaleX: { min: 1, max: 1.3 },
    scaleY: { min: 1, max: 2.9 },
    scaleZ: { min: 1, max: 1.3 },
  },
  {
    id: 2,
    name: "Isometric Pot",
    fov: { min: 10, max: 10 },
    density: { min: 0, max: 0 },
    strength: { min: 0, max: 0 },
    frequency: { min: 0, max: 0 },
    amplitude: { min: 0, max: 0 },
    intensity: { min: 0, max: 0 },
    scaleX: { min: 1.3, max: 1.6 },
    scaleY: { min: 1.9, max: 2.1 },
    scaleZ: { min: 1.7, max: 2.2 },
  },
  {
    id: 3,
    name: "Petal Pot",
    fov: { min: 11, max: 25 },
    density: { min: 1, max: 6 },
    strength: { min: 2, max: 4 },
    frequency: { min: 0, max: 10 },
    amplitude: { min: 0.1, max: 0.2 },
    intensity: { min: 0.3, max: 0.65 },
    scaleX: { min: 1.6, max: 2 },
    scaleY: { min: 1.4, max: 2.2 },
    scaleZ: { min: 1.5, max: 1.9 },
  },
  {
    id: 4,
    name: "Scaled X Zaha",
    fov: { min: 15, max: 20 },
    density: { min: 0.16, max: 2.18 },
    strength: { min: 1.5, max: 6 },
    frequency: { min: 0, max: 0.26 },
    amplitude: { min: 0, max: 1.6 },
    intensity: { min: 0.3, max: 0.4 },
    scaleX: { min: 4.5, max: 5 },
    scaleY: { min: 1, max: 2 },
    scaleZ: { min: 1.7, max: 2.3 },
  },
  {
    id: 5,
    name: "Stretched Blobby",
    fov: { min: 50, max: 90 },
    density: { min: 0.5, max: 0.8 },
    strength: { min: 8, max: 12 },
    frequency: { min: 0.5, max: 4 },
    amplitude: { min: 6, max: 16 },
    intensity: { min: 0.09, max: 0.12 },
    scaleX: { min: 2, max: 5 },
    scaleY: { min: 1, max: 2 },
    scaleZ: { min: 2, max: 5 },
  },
  {
    id: 6,
    name: "Blobby",
    fov: { min: 50, max: 90 },
    density: { min: 0.5, max: 0.8 },
    strength: { min: 8, max: 12 },
    frequency: { min: 0.5, max: 4 },
    amplitude: { min: 6, max: 16 },
    intensity: { min: 0.09, max: 0.12 },
    scaleX: { min: 1, max: 2 },
    scaleY: { min: 1, max: 2 },
    scaleZ: { min: 1, max: 2 },
  },
  {
    id: 7,
    name: "Space Gordita",
    fov: { min: 50, max: 90 },
    density: { min: 10, max: 70 },
    strength: { min: 1, max: 4 },
    frequency: { min: 0, max: 2 },
    amplitude: { min: 0, max: 2.7 },
    intensity: { min: 0.15, max: 0.54 },
    scaleX: { min: 3.2, max: 5 },
    scaleY: { min: 1, max: 1 },
    scaleZ: { min: 3.2, max: 5 },
  },
  {
    id: 8,
    name: "Gordita",
    fov: { min: 40, max: 60 },
    density: { min: 10, max: 70 },
    strength: { min: 1, max: 4 },
    frequency: { min: 0, max: 2 },
    amplitude: { min: 0, max: 2.7 },
    intensity: { min: 0.15, max: 0.54 },
    scaleX: { min: 1.7, max: 2.2 },
    scaleY: { min: 3, max: 4.3 },
    scaleZ: { min: 2, max: 2.9 },
  },
  {
    id: 9,
    name: "Stretched Flat Butterfly",
    fov: { min: 40, max: 60 },
    density: { min: 0.33, max: 10 },
    strength: { min: 1, max: 4 },
    frequency: { min: 0, max: 1 },
    amplitude: { min: 0, max: 0.4 },
    intensity: { min: 0.15, max: 0.8 },
    scaleX: { min: 3.8, max: 5 },
    scaleY: { min: 1, max: 4 },
    scaleZ: { min: 2, max: 5 },
  },
  {
    id: 10,
    name: "Flat Cactus",
    fov: { min: 35, max: 35 },
    density: { min: 20, max: 100 },
    strength: { min: 2, max: 4 },
    frequency: { min: 0, max: 0 },
    amplitude: { min: 0, max: 0.4 },
    intensity: { min: 0.2, max: 1.5 },
    scaleX: { min: 2, max: 5 },
    scaleY: { min: 1, max: 3.2 },
    scaleZ: { min: 2, max: 5 },
  },
  {
    id: 11,
    name: "Spiky Sun",
    fov: { min: 35, max: 35 },
    density: { min: 0.45, max: 20 },
    strength: { min: 0, max: 2 },
    frequency: { min: 0, max: 0 },
    amplitude: { min: 0, max: 0 },
    intensity: { min: 0.45, max: 2.65 },
    scaleX: { min: 2, max: 5 },
    scaleY: { min: 1, max: 2 },
    scaleZ: { min: 2, max: 5 },
  },
  {
    id: 12,
    name: "Pot on the Sun",
    fov: { min: 30, max: 30 },
    density: { min: 0.3, max: 0.45 },
    strength: { min: 0, max: 1 },
    frequency: { min: 0, max: 0 },
    amplitude: { min: 0, max: 0 },
    intensity: { min: 1, max: 10 },
    scaleX: { min: 2, max: 5 },
    scaleY: { min: 1, max: 1 },
    scaleZ: { min: 2, max: 5 },
  },
];
